// <auto-generated />
using System;
using DoZore.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DoZore.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DoZore.Api.Data.AnalyticsEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_version");

                    b.Property<string>("DataVersionHash")
                        .HasColumnType("text")
                        .HasColumnName("data_version_hash");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("Params")
                        .HasColumnType("jsonb")
                        .HasColumnName("params");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("Ts")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts");

                    b.HasKey("EventId")
                        .HasName("pk_analytics_events");

                    b.HasIndex("Name", "Ts")
                        .HasDatabaseName("ix_analytics_events_name_ts");

                    b.ToTable("analytics_events", (string)null);
                });

            modelBuilder.Entity("DoZore.Api.Data.CloudSave", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("PlayerId")
                        .HasName("pk_saves");

                    b.ToTable("saves", (string)null);
                });

            modelBuilder.Entity("DoZore.Api.Data.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("app_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("platform");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.HasKey("DeviceId")
                        .HasName("pk_devices");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_devices_player_id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("DoZore.Api.Data.GameDataVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bundle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bundle");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MinClientVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("min_client_version");

                    b.Property<string>("VersionHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version_hash");

                    b.HasKey("Id")
                        .HasName("pk_game_data_versions");

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasDatabaseName("ix_game_data_versions_is_active")
                        .HasFilter("is_active");

                    b.HasIndex("VersionHash")
                        .IsUnique()
                        .HasDatabaseName("ix_game_data_versions_version_hash");

                    b.ToTable("game_data_versions", (string)null);
                });

            modelBuilder.Entity("DoZore.Api.Data.LiveEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("Modifiers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("modifiers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("Id")
                        .HasName("pk_live_events");

                    b.HasIndex("StartsAt", "EndsAt")
                        .HasDatabaseName("ix_live_events_starts_at_ends_at");

                    b.ToTable("live_events", (string)null);
                });

            modelBuilder.Entity("DoZore.Api.Data.OfflineClaim", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AwayFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("away_from");

                    b.Property<DateTimeOffset>("AwayTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("away_to");

                    b.Property<long>("ClaimedAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("claimed_amount");

                    b.Property<long>("ComputedAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("computed_amount");

                    b.Property<long>("CountedSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("counted_seconds");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataVersionHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_version_hash");

                    b.Property<long>("GrantedAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("granted_amount");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.HasKey("Id")
                        .HasName("pk_offline_claims");

                    b.HasIndex("PlayerId", "CreatedAt")
                        .HasDatabaseName("ix_offline_claims_player_id_created_at");

                    b.ToTable("offline_claims", (string)null);
                });

            modelBuilder.Entity("DoZore.Api.Data.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("DoZore.Api.Data.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_refresh_tokens_player_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("DoZore.Api.Data.WeeklyScore", b =>
                {
                    b.Property<string>("WeekId")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("week_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset>("ReachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reached_at");

                    b.Property<long>("Score")
                        .HasColumnType("bigint")
                        .HasColumnName("score");

                    b.HasKey("WeekId", "PlayerId")
                        .HasName("pk_weekly_scores");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_weekly_scores_player_id");

                    b.HasIndex("WeekId", "Score", "ReachedAt")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("ix_weekly_scores_week_id_score_reached_at");

                    b.ToTable("weekly_scores", (string)null);
                });

            modelBuilder.Entity("DoZore.Api.Data.CloudSave", b =>
                {
                    b.HasOne("DoZore.Api.Data.Player", null)
                        .WithOne()
                        .HasForeignKey("DoZore.Api.Data.CloudSave", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saves_players_player_id");
                });

            modelBuilder.Entity("DoZore.Api.Data.Device", b =>
                {
                    b.HasOne("DoZore.Api.Data.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_players_player_id");
                });

            modelBuilder.Entity("DoZore.Api.Data.OfflineClaim", b =>
                {
                    b.HasOne("DoZore.Api.Data.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_offline_claims_players_player_id");
                });

            modelBuilder.Entity("DoZore.Api.Data.RefreshToken", b =>
                {
                    b.HasOne("DoZore.Api.Data.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_players_player_id");
                });

            modelBuilder.Entity("DoZore.Api.Data.WeeklyScore", b =>
                {
                    b.HasOne("DoZore.Api.Data.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_weekly_scores_players_player_id");
                });
#pragma warning restore 612, 618
        }
    }
}
